### ISSUE TITLE
研究生模板公式编号问题

### ISSUE THREAD

**Issue by JJYdesu** [sikouhjw/gdutthesis-Word#17]
作者你好：
在后面的章节（如第二章第三章）插入公式，编号也是1.xx开头的，这个应该是bug吧。
谢谢

**Comment by sikouhjw** [comment]
是 bug，我更倾向于是 Word 自身的问题，由于本模板是使用多级列表来编号，

**Comment by sikouhjw** [comment]
是 bug，我更倾向于是 Word 自身的问题，由于本模板是使用多级列表来编号，而 Word 有可能将模板的多级列表中的『将级别链接到样式』清空，因此需要重新设置『将级别链接到样式』。

解决方案：
1. 点开『开始』选项卡中的『段落』组中的『多级列表』，右键修改『列表样式』中的『章节』样式，点击『格式』、『编号』，级别 1 的『将级别链接到样式』选择『标题 1』，级别 2 的『将级别链接到样式』选择『section』，级别 3 的『将级别链接到样式』选择『subsection』，级别 4 的『将级别链接到样式』选择『subsubsection』，级别 5 的『将级别链接到样式』选择『参考文献』，级别 7 的『将级别链接到样式』选择『附录-chapter』；
2. 此时样式已经与多级列表绑定好了，还需要将级别 8 的『重新开始列表的间隔』取消勾再打勾，刷新编号。

**Comment by sikouhjw** [comment]
相关问题：
- 《List Style Loses "Link Level to Style"》[^1]
- 《Multilevel Lists Lose Link to Styles》[^2]
- 《Heading styles come "unlinked" from Multi-level list levels after save.》[^3]

[^1]: https://answers.microsoft.com/en-us/msoffice/forum/all/list-style-loses-link-level-to-style/fbc7fcb7-ae41-4305-80fc-250ffb4f7aab
[^2]: https://groups.google.com/g/microsoft.public.word.numbering/c/sHUrDDQSuAM?pli=1
[^3]: https://www.msofficeforums.com/word/18734-heading-styles-come-unlinked-multi-level-list.html

**Comment by DandelionRi** [comment]
其实是图文集中公式的域代码本应该用math2，但是现实情况却是word本身的math，只要在文中公式的编号右键点击编辑域，选择ListNum的math2就好（一个个修改）。当然，这是针对已经完成文章的情况，因为按作者给的方案，在自然段中的公式也会随之变化，多出编号。

**Comment by sikouhjw** [comment]
> 其实是图文集中公式的域代码本应该用math2，但是现实情况却是word本身的math，只要在文中公式的编号右键点击编辑域，选择ListNum的math2就好（一个个修改）。当然，这是针对已经完成文章的情况，因为按作者给的方案，在自然段中的公式也会随之变化，多出编号。

“自然段中的公式也会随之变化，多出编号”是什么意思？

**Comment by DandelionRi** [comment]
> > 其实是图文集中公式的域代码本应该用math2，但是现实情况却是word本身的math，只要在文中公式的编号右键点击编辑域，选择ListNum的math2就好（一个个修改）。当然，这是针对已经完成文章的情况，因为按作者给的方案，在自然段中的公式也会随之变化，多出编号。
> 
> “自然段中的公式也会随之变化，多出编号”是什么意思？

就是本来文章中的公式应该会另起一段嘛，但是在非公式段的陈述段中会用到一些符号，这些符号我会设置公式math的格式，如果按照您给出的解决方案，在文章已形成初稿的情况下，会导致陈述段中的带公式格式的符号多出小尾巴——编号

**Comment by sikouhjw** [comment]
> 就是本来文章中的公式应该会另起一段嘛，但是在非公式段的陈述段中会用到一些符号，这些符号我会设置公式math的格式，如果按照您给出的解决方案，在文章已形成初稿的情况下，会导致陈述段中的带公式格式的符号多出小尾巴——编号

之前欠考虑了，研究生模板的域列表名是 `GDUT`，就没有这个问题
