### ISSUE TITLE
打开错误问题

### ISSUE THREAD

**Issue by pancodex** [sikouhjw/gdutthesis-Word#18]
原本模版没问题，但是某一天我在往里面添加内容的时候再打开就显示“很抱歉，无法打开docx，因为内容有问题”，如下图所示
![image](https://user-images.githubusercontent.com/48055114/214477251-b15d451e-ef60-4dff-82f4-540944f940c1.png)
我用的是word2016版本，即便是恢复word内容后另存为依旧是存在该问题，请问作者有遇到过这个问题吗。

**Comment by pancodex** [comment]
解决了，是因为插入TC 域代码时出现bug所导致的，在Office16、19、365都会出现，避免办法就是使用19版本的word通过插入图文集中的章节标题然后填充TC域代码，这样就不会出现上述问题。

**Comment by sikouhjw** [comment]
> 是因为插入TC 域代码时出现bug所导致的

你是手动插入 TC 域代码？

**Comment by pancodex** [comment]
> 你是手动插入 TC 域代码？

不是，是双语标题的TC域代码，将代码复制再修改的时候就容易导致出错然后无法打开该文档。
