### ISSUE TITLE
关于研究生论文模版中图题注的字体问题

### ISSUE THREAD

**Issue by pancodex** [sikouhjw/gdutthesis-Word#19]
您好，我发现在学校提供的“广东工业大学研究生学位论文格式模板（2022年9月）.docx”文件中，图片题注的**标签格式**为“**中文：黑体** 英文：新罗马加粗”，但我在使用最新模版的插入图文集中的插入单图时，发现图片题注的标签格式为“**中文：黑体加粗**，英文：新罗马加粗”。（不同点在于题注标签的中文样式，学校模版没加粗，表格标签同样存在该问题）
请问这是学校文件的纰漏吗，需要我们自行修改吗？

**Comment by sikouhjw** [comment]
Word 样式做不到『中文不加粗、英文加粗』，只能统一加粗和不加粗，因此这里选择统一加粗。

即使手动将中文取消加粗，将其保存为自动图文集后再使用仍然是加粗状态，因此只能在使用自动图文集后再手动取消加粗。

我个人认为这里是无关紧要的，『黑体』是无衬线体，『Times New Roman』是衬线体，不应该一起使用，而是建议『宋体+Times New Roman+加粗』或者『黑体+Arial+不加粗』。学校这里是将宋体的粗体映射为黑体，跟 LaTeX 中 ctex 宏集（在 win 下）的行为一致，但映射为黑体是无奈之举，因为中易宋体没有对应粗体可用。我认为直接在 Word 里用伪粗体（直接加粗）就好了，所以 Word 模板选择『黑体+Times New Roman+加粗』，LaTeX 模板选择『宋体+Times New Roman+加粗』。

**Comment by pancodex** [comment]
好的明白，感谢！
