### ISSUE TITLE
目录无法显示附录

### ISSUE THREAD

**Issue by Fantasitao** [sikouhjw/gdutthesis-Word#20]
大佬你好，正文后面添加了附录之后，目录这边好像无法更新出对应的附录信息。
![Snipaste_2023-04-19_22-55-28](https://user-images.githubusercontent.com/69242388/233115642-f4114b7f-0e2f-40fd-ba84-2a5fbd4fe260.png)
![Snipaste_2023-04-19_22-55-38](https://user-images.githubusercontent.com/69242388/233115655-d3b69e87-f450-44f1-ab30-c77d77ec6ca4.png)

**Comment by sikouhjw** [comment]
本科模板忘把附录加进去了，可以用以下步骤去添加：
1. 『引用』->『目录』->『自定义目录』
2. 『选项』->将『有效样式』中的『标题 7,附录-chapter』的『目录级别』设为 `1`
3. 『确定』->『确定』->『确定』

**Comment by yangwangkong** [comment]
多谢，我说怎么查重把附录都给查了
