### ISSUE TITLE
交叉引用时无法引用图表，图表是通过自动图文集添加的

### ISSUE THREAD

**Issue by horacehht** [sikouhjw/gdutthesis-Word#24]
![image](https://github.com/sikouhjw/gdutthesis-Word/assets/76420226/81656c3c-1e9e-45d2-b6fd-326a7f4d394d)
![image](https://github.com/sikouhjw/gdutthesis-Word/assets/76420226/7cc65b82-b3e5-4b5a-8c3f-2980063ddc5e)

**Comment by sikouhjw** [comment]
请阅读 wiki[^1]后使用。

[^1]: https://github.com/sikouhjw/gdutthesis-Word/wiki#%E8%87%AA%E5%8A%A8%E5%9B%BE%E6%96%87%E9%9B%86%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
