### ISSUE TITLE
chapter样式与格式模板的段落不一致

### ISSUE THREAD

**Issue by Leefive** [sikouhjw/gdutthesis-Word#26]
附件3：广东工业大学研究生学位论文格式模板（2023年9月）.doc 模板文件中给出的
**参考文献
攻读学位期间取得与学位论文相关的成果 
致谢**
段后0行
![image](https://github.com/sikouhjw/gdutthesis-Word/assets/42556239/c0b2cdc9-7693-4e25-a517-eb2711176fcb)
而上面三个一级标题属于模板中的chapter样式，但是模板中的chapter样式是段后1行
![image](https://github.com/sikouhjw/gdutthesis-Word/assets/42556239/3649cd4e-8a2f-4485-8854-e0926750c664)

**Comment by sikouhjw** [comment]
应该是之前把 `\chapter` 改了，但是 `\chapter*` 忘改了。现在先手动调一下吧。
