### ISSUE TITLE
插入论文引用，导出pdf时会自带章节编号

### ISSUE THREAD

**Issue by horacehht** [sikouhjw/gdutthesis-Word#27]
![image](https://github.com/sikouhjw/gdutthesis-Word/assets/76420226/b01b951d-e429-40df-a41f-fe8f6918f1c3)
如题所示，通过“交叉引用”插入的文献会自带章节编号，比如4.5[1]中的4.5，可以手动删除后引用中的4.5变为[1]。
但是当我将word文档导出为pdf时，word中所有引用又变为了4.5[1]的形式（pdf显示的引用形式也是4.5[1]），这个问题十分困扰。

**Comment by sikouhjw** [comment]
使用 `段落编号(无上下文)` 即可。

**Comment by horacehht** [comment]
谢谢作者，回复太快了，感激！
