### ISSUE TITLE
本科论文模板中的字母和数字应全为Times New Roman体

### ISSUE THREAD

**Issue by jingjue** [sikouhjw/gdutthesis-Word#28]
**标准**：根据[附件1-2024届毕业设计（论文）手册.pdf](https://github.com/sikouhjw/gdutthesis-Word/files/15189652/1-2024.pdf)第16~18页的要求，本科论文中的西文和数字应全为Times New Roman 体。

**问题**：已知《本科—正文.dotx》中包括但不限于以下的字母和数字非Times New Roman 体
1、封面的日期数字；
2、目录的标题和页码数字；
3、各级标题的数字；
4、页码的数字；

**临时解决方法**：
1、对于完成的论文，全选全文，然后在字体中将西文字体改为Times New Roman 体

**Comment by sikouhjw** [comment]
正如 https://github.com/sikouhjw/gdutthesis/discussions/44#discussioncomment-2357996 所说，相关规定是不合理的，所以我没有设置成「全部 TNR」。

从实践的角度，Arial 也能通过审查；甚至非「（中易）宋体」也能通过审查[^1]。

结论：如果导师/学院/图书馆认为需要修改，全局修改也不麻烦。

[^1]: 李祉延. 近似贝叶斯推断下的线谱估计算法研究[D]. 广东工业大学, 2022. DOI: [10.27029/d.cnki.ggdgu.2022.001133](https://doi.org/10.27029/d.cnki.ggdgu.2022.001133).
