### ISSUE TITLE
正文与引用序号的字号不同请问如何设置

### ISSUE THREAD

**Issue by dltsam** [sikouhjw/gdutthesis-Word#29]
你好我在使用这个模板的同时也使用了zotero参考文献模板，在格式要求中，[广东工业大学研究生学位论文撰写规范（2023年9月）.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14872337/2023.9.docx) 
![image](https://github.com/user-attachments/assets/2cb7cdc0-14d2-4563-84cf-d22656ec1693)
正文为小四，而引用序号上标为小五，请问可以怎样设置进行区分？

**Comment by sikouhjw** [comment]
你好，可以看看 [https://github.com/zotero-chinese/styles](https://github.com/zotero-chinese/styles)。

**Comment by dltsam** [comment]
我在 https://github.com/zotero-chinese/styles 中也提交了相关的commit 
https://github.com/zotero-chinese/styles/issues/399#issuecomment-2458777010
zotero开发者建议我使用word样式进行分类，但似乎样式应该也不方便吧，应该需要使用域代码或vba控制。

**Comment by sikouhjw** [comment]
我没用过 zotero，用样式去控制的话，需要对每一个上标都选中-点击样式。

注意样式类型选择“字符”。
![图片](https://github.com/user-attachments/assets/8b08977d-4eb5-44f4-a518-40267cb60f2a)

**Comment by dltsam** [comment]
> 我没用过 zotero，用样式去控制的话，需要对每一个上标都选中-点击样式。
> 
> 注意样式类型选择“字符”。 ![图片](https://private-user-images.githubusercontent.com/49770925/383465527-8b08977d-4eb5-44f4-a518-40267cb60f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODI0NDMsIm5iZiI6MTczMDg4MjE0MywicGF0aCI6Ii80OTc3MDkyNS8zODM0NjU1MjctOGIwODk3N2QtNGViNS00NGY0LWE1MTgtNDAyNjdjYjYwZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMzI2ZjVjMDJhNDI1OThhNmVjNTA2MTQxNDRkNjA3NDA0NzRjMjM1M2EzNTc5MGJmNWVlOTdhNDI5MzY2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1mjhaCfstlEoCh85_oTz9tUg7rCzlODYLSJ522XyFMA)

好的谢谢！
